README.md
Adding some Arduino and PICs projects libraries
=> Adding some Arduino and PICs projects libraries

README.md
My small, humble contribs in Erlang and other languages.
=> Adding some contributions by @codeadict

README.md
=> Update README.md with PowerM

README.md
Adding new Cuban open source repos ...
=> Adding fperdigon(bosito7) software.

README.md
Reverts cuban-opensourcers/cuban-opensource#33
Please, sort your entry
=> Revert "Add a Cuban Node.js framework from Raptor Project"

README.md, publish.md
=> Add Mailad, mailad is a work in progress

README.md
Base structure for a web application using the Flask micro-framework and the MVC software architecture pattern.
=> Add the Flask Base

README.md
=> Fix viajes-uh description

README.md
- Binary Coffee API
- Binary Coffee frontend
- Binary Coffee administration frontend
- Binary Coffee bot
- string-mismatch NodeJS library
=> New projects added to the list

README.md
A simple Django app to manage customers.
=> Added Django-MisClientes

README.md
Also re-arange the pic and arduino section alphabetically, some typos and grammar fixes
=> Incusion of esp8266_wx_station arduino project

README.md
=> mdexportab addition

README.md
@glpzzz, these repositories will not be public from now on, so I've removed their links here.
=> remove: Removed deprecated links

README.md
Ahora ya arreglé el problema. Son las 4AM, no me fijé en la categoría superior que es para las Web Applications ya terminadas.
=> Fixed the huge typo

README.md
Add Picta Downloader GUI to the README.md
=> Add Picta Downloader GUI project

README.md
Add SimpleStaticServer: https://github.com/PhaserEditor2D/SimpleStaticServer/
=> Add SimpleStaticServer

README.md
Adding 2 Telegram bots and a web application
=> add: gatsby-cv-maker to Web Applications

README.md
- Adding click-handler 
- Browser extensions header
- Adding Zen Twitter
- Creating UI Libraries header
- Adding Multi Steps Form Component for Bootstrap
=> Adding Zen Twitter, click-handler and Steps Component for Bootstrap

README.md
Updates Phaser Editor 2D links
=> Updates Phaser Editor 2D links

README.md
Hola equipo,
En esta pull request les informo que he cambiado el nombre de mi proyecto a suitetecsa-sdk-python.
Este cambio de nombre refleja mejor el enfoque y propósito del proyecto, y espero que sea más fácil de recordar y encontrar para los usuarios y colaboradores potenciales.
Agradezco cualquier comentario o sugerencia que puedan tener sobre este cambio de nombre o sobre cualquier aspecto del proyecto en general.
¡Gracias por su tiempo y consideración!
=> Cambio de nombre y url
